---
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1

before_install:
  - sudo apt-get install nunit-console
script:
  - dotnet restore
  - dotnet build **/project.json --configuration Release
  - nunit-console src/DotLiquid.Tests/bin/Release/netcoreapp1.0/DotLiquid.Tests.dll src/DotLiquid.Tests/bin/Release/net451/win7-x64/DotLiquid.Tests.dll
 