version: 1.9.0-ci{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.9.0"
  assembly_file_version: "1.9.0"
  assembly_informational_version: "1.9.0-ci{build}"

build:
  project: src/DotLiquid.sln
  publish_nuget: true

artifacts:
- path: build\pkg\*.nupkg
  name: Nuget Package
- path: '**\*.nuspec'

deploy:
- provider: NuGet
  api_key:
    secure: LrIeQprS+E5FzLkdKGYIYHXy/86Kt8YVhTa4J/VhLzGUO+yXnqI+GxDR+K5Wj/VL
  skip_symbols: true
  artifact: /.*\.nupkg/
