# Build script for dotliquid, see https://www.appveyor.com/docs/appveyor-yml for reference
version: 2.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(GIT_HASH)"

build:
  verbosity: minimal # quiet|minimal|normal|detailed
  project: src/DotLiquid.sln
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
- path: build\pkg\*.nupkg
  name: Nuget Package

nuget:
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: LrIeQprS+E5FzLkdKGYIYHXy/86Kt8YVhTa4J/VhLzGUO+yXnqI+GxDR+K5Wj/VL
  skip_symbols: false
  artifact: /.*\.nupkg/

notifications:
  - provider: Email
    to:
      - henrik@haf.se
    on_build_status_changed: true
