version: 2.0.0

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "2.0.0-ci{build}"

build:
  project: src/DotLiquid.sln
  publish_nuget: true

artifacts:
- path: build\pkg\*.nupkg
  name: Nuget Package

nuget:
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: LrIeQprS+E5FzLkdKGYIYHXy/86Kt8YVhTa4J/VhLzGUO+yXnqI+GxDR+K5Wj/VL
  skip_symbols: false
  artifact: /.*\.nupkg/
